### ISSUE TITLE
adding content does not seem to work.

### ISSUE THREAD

**Issue by uskudarli** [TalatCikikci/BounSwe573Repo#2]
I added a product (Keci Peyniri _ and a Producer ( Ismet Cokbilir).

When I add it and then go to see them I see the same -- probably fake -- product and producer list.

When I add products or producers I do not see them, is there any backend functionality?

**Comment by TalatCikikci** [comment]
Yes, when this issue was created, the backend functionality was not yet complete.

Content can now be added to the portal.
